---
- name: naam
  hosts: proxmox
  vars_files: 
    - ./vars/proxmox.yml
    - ./vars/vault.yml
  roles:
    # - windows_server_2016 
  tasks:

    - name: Download vyos 1.5:w
      ansible.builtin.get_url:
        url: https://github.com/vyos/vyos-rolling-nightly-builds/releases/download/1.5-rolling-202401250024/vyos-1.5-rolling-202401250024-amd64.iso 
        dest: /var/lib/vz/template/iso/vyos-1.5.iso
        mode: '0440'
        # checksum: ed25519:zgorkgX9RO630BvM5D14vkqq5i+Qaq9AE4l3PkaeHzPpncS4D54ZuaDYiT+6yPCk12MI8dWxztVmln+xztvgCg==

    - name: Create new VM with minimal options
      community.general.proxmox_kvm:
        api_user: "{{ proxmox_api_user }}" 
        api_token_id: "{{ proxmox_api_id }}" 
        api_token_secret: "{{ proxmox_api_secret }}" 
        api_host: "{{ proxmox_api_host }}" 
        node: "{{ proxmox_node_name }}" 
        name: vyos 
        # disk: local:35gb
        ide: '{"ide0":"local:iso/vyos-1.5.iso,media=cdrom"}'
